### ISSUE TITLE
CI: verify memory layout of test-app

### ISSUE THREAD

**Issue by japaric** [knurling-rs/flip-link#25]
CI compiles the `test-flip-link-app` (binary) crate to the ARM Cortex-M architecture as an 'it links' test.

We should extend this test and also check that the memory layout of the output ELF is indeed "flipped".

Steps:
1. use the `object` crate to parse the output ELF
2. read the `.vector_table` linker section and extract the `initial SP pointer` value
3. find the boundaries of `static RAM` (the `.bss`, `.data` and `.uninit` linker sections)
4. `initial SP pointer` (2) should be lower/smaller than the lowest boundary of `static RAM`

These steps could be done in a test file in the root (e.g. `test/verify.rs`): the test function would build the test-app and then verify its memory layout.
This `cargo test` will run the unit tests in `src/main.rs` as well as this new test.

**Comment by Urhengulas** [comment]
> b. read the `.vector_table` linker section and extract the 'initial SP pointer' value

Hi @japaric, I am struggeling to figure out how to extract the initial stack pointer from the vector table. Can you please give me a pointer for this?
