### ISSUE TITLE
CI: add regression test for #22

### ISSUE THREAD

**Issue by japaric** [knurling-rs/flip-link#26]
Add regression test for #22.

- add a new test-app folder / package (like `test-flip-link-app`)
- have this app use a manual `memory.x` file -- easiest way to do this may be to *not* use a HAL
- have the `memory.x` use an `INCLUDE` like this:
``` text
MEMORY
{
  FLASH : ORIGIN = 0x00000000, LENGTH = 256K
  RAM : ORIGIN = 0x20000000, LENGTH = 64K
}

INCLUDE empty.x
```
- create an empty `empty.x` file next to the `memory.x`
- have CI cross compile this new test-app to ARM Cortex-M ("it links" test)

**Comment by Urhengulas** [comment]
Question: The new test app shouldn't have a build-script copying the `memory.x` and `empty.x` to the `OUT_DIR`, should it?

**Comment by japaric** [comment]
generally speaking the build script that copies the linker is
- required in *libraries*
- *not* required in *applications* because the linker will see the linker scripts if they are next to the app's Cargo.toml (because Cargo invokes the linker from the root of the Cargo project)

still, it doesn't hurt to have it in applications. I imagine that if you have a Cargo workspace and your app package where the linker scripts are is *not* the root of the workspace then the linker *may* not find it but haven't tested this before (unsure if Cargo `cd`s into a package when building it or if it stays in the root of the workspace while building every package)
