### ISSUE TITLE
Support rust lld @file command line arguments

### ISSUE THREAD

**Issue by great-houk** [knurling-rs/flip-link#95]
I don't know exactly why this is a thing, but when the arguments passed to rust lld are too long (?) it gets passed a special argument [(at the bottom of this page)](https://doc.rust-lang.org/rustc/command-line-arguments.html) that refers to a file. Currently, flip-link doesn't seem to handle this.

I've made a fork that "fixes" the bug by just hardcoding support and using a bunch of unwraps [here](https://github.com/great-houk/flip-link/tree/at-file-args), but I imagine someone who knows how linkers work and can make a good solution should be the one to make the PR.

**Comment by jonathanpallant** [comment]
It's because operating systems place a fairly small upper bound on the length of a command line. I think it's 8191 bytes on Windows. We should handle this, I agree.

**Comment by Urhengulas** [comment]
@great-houk The documentation does not state that the argument can only be in last position. From reading the docs I'd assume it can be in any. Unless it is specified somewhere else we should support it in any position.

Also can there only be one of those arguments or also multiple?

Can you open a PR with your changes? I think you can get rid of some unwraps by using `if let` and the like.

Btw, if you click on a heading you can link to it directly: https://doc.rust-lang.org/rustc/command-line-arguments.html#path-load-command-line-flags-from-a-path
